packages:
    - "apps/*"
    - "services/*"
engineStrict: true
saveExact: true
strictPeerDependencies: true
frozenLockfile: false
sharedWorkspaceLockfile: true
overrides:
  source-map-js: ^1.2.2
minimumReleaseAge: 1440
strictSsl: true
preferOffline: true
audit:
  level: moderate
verifyStoreIntegrity: false
strictStorePkgContentCheck: false
blockExoticSubdeps: true
allowBuilds:
  esbuild: true
  sharp: true
verifyDepsBeforeRun: false
ignoreScripts: false
manage-package-manager-versions: false
supportedArchitectures:
  os: [linux, android]
  cpu: [x64, arm64]
